- name: Installer Docker sur les hôtes
  hosts: web
  become: true

  tasks:
    - name: Installer les dépendances
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Télécharger la clé GPG de Docker
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Installer Docker Engine
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: S'assurer que Docker est démarré
      service:
        name: docker
        state: started
        enabled: true
