- name: CrÃ©er le dossier site et un index.html
  hosts: web
  become: true

  tasks:
    - name: CrÃ©er le dossier /home/High/site
      file:
        path: /home/High/site
        state: directory
        owner: High
        group: High
        mode: '0755'

    - name: CrÃ©er un fichier index.html
      copy:
        dest: /home/High/site/index.html
        content: "<h1>Hello Juan ðŸ‘Š â€” Bienvenue sur Nginx !</h1>"
        owner: High
        group: High
        mode: '0644'
